function H = SNH_dF2(in1,C,D)
%SNH_DF2
%    H = SNH_DF2(IN1,C,D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Nov-2020 15:38:57

%Version: 1.0
F1_1 = in1(1);
F1_2 = in1(3);
F2_1 = in1(2);
F2_2 = in1(4);
t2 = C.*2.0;
t3 = F1_1.*F2_2;
t4 = F1_2.*F2_1;
t5 = -C;
t6 = D.*F1_1.*F1_2.*2.0;
t7 = D.*F1_1.*F2_1.*2.0;
t10 = D.*F1_2.*F2_2.*2.0;
t11 = D.*F2_1.*F2_2.*2.0;
t8 = D.*t3.*2.0;
t9 = D.*t4.*2.0;
t12 = -t3;
t13 = -t6;
t14 = -t7;
t15 = -t10;
t16 = -t11;
t17 = t4+t12+1.0;
t18 = D.*t17.*2.0;
t19 = -t18;
t20 = C+t9+t18;
t21 = t5+t8+t19;
H = reshape([t2+D.*F2_2.^2.*2.0,t15,t16,t21,t15,t2+D.*F1_2.^2.*2.0,t20,t13,t16,t20,t2+D.*F2_1.^2.*2.0,t14,t21,t13,t14,t2+D.*F1_1.^2.*2.0],[4,4]);
