function g = neohookean_dF(in1,C,D)
%NEOHOOKEAN_DF
%    G = NEOHOOKEAN_DF(IN1,C,D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Nov-2020 13:01:11

%Version: 1.0
F1_1 = in1(1);
F1_2 = in1(3);
F2_1 = in1(2);
F2_2 = in1(4);
t2 = F1_1.^2;
t3 = F1_2.^2;
t4 = F2_1.^2;
t5 = F2_2.^2;
t6 = F1_1.*F2_2;
t7 = F1_2.*F2_1;
t8 = -t6;
t9 = -t7;
t12 = t2+t3+t4+t5;
t10 = t6+t9;
t11 = t7+t8+1.0;
t13 = 1.0./t10.^(2.0./3.0);
t14 = 1.0./t10.^(5.0./3.0);
g = [C.*(F1_1.*t13.*2.0-F2_2.*t12.*t14.*(2.0./3.0))-D.*F2_2.*t11.*2.0;C.*(F2_1.*t13.*2.0+F1_2.*t12.*t14.*(2.0./3.0))+D.*F1_2.*t11.*2.0;C.*(F1_2.*t13.*2.0+F2_1.*t12.*t14.*(2.0./3.0))+D.*F2_1.*t11.*2.0;C.*(F2_2.*t13.*2.0-F1_1.*t12.*t14.*(2.0./3.0))-D.*F1_1.*t11.*2.0];
