function g = SNH_dF(in1,C,D)
%SNH_DF
%    G = SNH_DF(IN1,C,D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Nov-2020 15:38:57

%Version: 1.0
F1_1 = in1(1);
F1_2 = in1(3);
F2_1 = in1(2);
F2_2 = in1(4);
t2 = F1_1.*F2_2;
t3 = F1_2.*F2_1;
t4 = -t2;
t5 = t3+t4+1.0;
g = [C.*F1_1.*2.0-C.*F2_2-D.*F2_2.*t5.*2.0;C.*F1_2+C.*F2_1.*2.0+D.*F1_2.*t5.*2.0;C.*F1_2.*2.0+C.*F2_1+D.*F2_1.*t5.*2.0;-C.*F1_1+C.*F2_2.*2.0-D.*F1_1.*t5.*2.0];
